/*
* Copyright (c) 2000-2015 Samsung Electronics Co., Ltd All Rights Reserved
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*
*/




#ifndef __DEF_MF_UG_RESOURCE_H_
#define __DEF_MF_UG_RESOURCE_H_

#include "mf-ug-conf.h"

#define MF_UG_LABEL_PHONE			"IDS_MF_BODY_DEVICE_MEMORY_ABB"
#define MF_UG_LABEL_SELECTED			"IDS_COM_BODY_PD_SELECTED"
#define MF_UG_LABEL_MMC				"IDS_MF_BODY_SD_CARD_ABB"
#define MF_UG_LABEL_NO_FILES			"IDS_COM_BODY_NO_FILES"
#define MF_UG_LABEL_MYFILES			"IDS_COM_BODY_MY_FILES"
#define MF_UG_LABEL_OK				"IDS_COM_SK_OK"
#define MF_UG_LABEL_NO_RESULT			"IDS_COM_BODY_NO_ITEMS"
#define MF_UG_LABEL_DONE			"IDS_COM_SK_DONE"
#define MF_UG_LABEL_CANCEL			"IDS_COM_SK_CANCEL"
#define MF_UG_LABEL_DELETE			"IDS_COM_BODY_DELETE"
#define MF_UG_LABEL_UNSUPPORT_FILE_TYPE		"IDS_COM_BODY_UNSUPPORTED_FILE_TYPE"
#define MF_UG_LABEL_SELECT_ALL			"IDS_COM_BODY_SELECT_ALL"
#define MF_UG_LABEL_YES				"IDS_COM_SK_YES"
#define MF_UG_LABEL_NO				"IDS_COM_SK_NO"
#define MF_UG_LABEL_BACK			"IDS_COM_SK_BACK"
#define MF_UG_LABEL_ADD				"IDS_COM_SK_ADD"
#define MF_UG_LABEL_DELETE			"IDS_COM_BODY_DELETE"
#define MF_UG_LABEL_FAILED			"IDS_COM_POP_FAILED"
#define MF_UG_LABEL_SUCCESS			"IDS_COM_POP_SUCCESS"
#define MF_UG_LABEL_FAILED			"IDS_COM_POP_FAILED"
#define MF_UG_BUTTON_LABEL_DEL		"IDS_MF_POP_DELETE_Q"
#define MF_UG_LABEL_ADD_FAILED		"IDS_MUSIC_POP_UNABLE_TO_ADD_SOME_ITEMS_DONT_EXIST"
#define MF_UG_POP_TITLE_OPERATION_ERROR 	"IDS_COM_BODY_OPERATION_FAILED"
#define MF_UG_LABEL_UNABLE_TO_PLAY_DURING_CALL "IDS_MF_POP_UNABLE_TO_PLAY_DURING_CALL"
#define MF_UG_LABEL_UNABLE_TO_PLAY_ERROR_OCCURRED  "IDS_MUSIC_POP_UNABLE_TO_PLAY_ERROR_OCCURRED"
#define MF_UG_LABEL_GET_NAME_FAILED		"IDS_MF_POP_INVALID_FILE_NAME"
#define MF_UG_LABEL_NAME_INVALID		"IDS_MF_POP_INVALID_FILE_NAME"
#define MF_UG_LABEL_ILLEGAL_CHAR		"IDS_VR_POP_INVALID_CHARACTER_ENTERED_TRY_AGAIN"
#define MF_UG_LABEL_DUP_NAME			"IDS_COM_POP_ALREDY_EXISTS"
#define MF_UG_LABEL_OPER_READ_ONLY		"Operation failed: Read Only Area"
#define MF_UG_LABEL_CREATE_DIR_FAILED		"IDS_COM_POP_FAILED"
#define MF_UG_LABEL_EMPTY_FOLDER_NAME		"IDS_MF_POP_ERR_FOLDER_NAME_EMPTY"
#define MF_UG_LABEL_DEFAULT_RINGTONE		"IDS_MF_OPT_DEFAULT_RINGTONE"
#define MF_UG_LABEL_MAX_CHARACTER_REACHED	"IDS_COM_POP_MAXIMUM_NUMBER_OF_CHARACTERS_REACHED"
#define MF_UG_LABEL_CREATE			"IDS_COM_BODY_CREATE_FOLDER"
#define MF_UG_LABEL_SILENT			"IDS_ST_BODY_PHONEPROFILES_SILENT"
#define MF_UG_LABEL_NOT_ENOUGH_SPACE		"IDS_COM_POP_NOT_ENOUGH_MEMORY"
#define MF_UG_LABEL_FOLDER			"IDS_COM_POP_FOLDER"
#define MF_UG_LABEL_CONNECT_FAILED		"IDS_COM_POP_CONNECTION_FAILED"
#define MF_UG_LABEL_IMPORT_CHAP			dgettext("ug-myfile-efl", "IDS_COM_OPT_IMPORT")
#define MF_UG_LABEL_DOCUMENTS			"IDS_MF_BODY_DOCUMENTS"
#define MF_UG_LABEL_SELECT_ITEMS			"IDS_MF_HEADER_SELECT_ITEMS"
#define MF_UG_LABEL_PROCESSING			"IDS_COM_POP_PROCESSING"
#define MF_UG_LABEL_SEARCH			"IDS_COM_BODY_SEARCH"
#define MF_UG_LABEL_DEFAULT_NOTIFICATION_SOUND		"IDS_ST_BODY_DEFAULT_NOTIFICATION_SOUND_ABB"
#define MF_UG_LABEL_REACH_MAX_SHARE_COUNT	"IDS_IV_POP_YOU_CAN_SELECT_UP_TO_PD_ITEMS"
#define MF_UG_LABEL_DONE_CAP			"IDS_TPLATFORM_ACBUTTON_DONE_ABB"
#define MF_UG_LABEL_CANCEL_CAP			"IDS_TPLATFORM_ACBUTTON_CANCEL_ABB"
#define MF_UG_LABEL_MAXIMUM_SIZE			"IDS_IM_POP_MAXIMUM_SIZE_OF_FILES_EXCEEDED"


#endif

